from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]
original_dir = Path(__file__).parent / 'original'
original_dir.mkdir(exist_ok=True)
files = [ROOT / 'article/manuscript.tex', *sorted((ROOT / 'article/chapters').glob('*.tex')),
         *sorted((ROOT / 'article/figures').glob('*.tex')), ROOT / 'article/references.bib']
texts = {}
newlines = {}
for path in files:
    data = path.read_bytes()
    rel = path.relative_to(ROOT)
    copy = original_dir / rel
    copy.parent.mkdir(parents=True, exist_ok=True)
    if not copy.exists():
        copy.write_bytes(data)
    newlines[path] = '\r\n' if b'\r\n' in data else '\n'
    texts[path] = data.decode('utf-8').replace('\r\n', '\n')

def replace(name, old, new):
    path = ROOT / 'article' / name
    assert old in texts[path], (name, old[:100])
    texts[path] = texts[path].replace(old, new)

def paragraph(name, starts, new):
    path = ROOT / 'article' / name
    blocks = texts[path].split('\n\n')
    hits = [i for i, block in enumerate(blocks) if block.startswith(starts)]
    assert len(hits) == 1, (name, starts, hits)
    blocks[hits[0]] = new
    texts[path] = '\n\n'.join(blocks)

C1 = 'chapters/01_research_problem.tex'
replace(C1, r'\chapter{Introduction: Research Problem and Purpose}', r'\chapter{Introduction and Research Purpose}')
paragraph(C1, 'Wastewater treatment is an engineering response', r'''Wastewater treatment removes pollutants or changes them into forms that reduce their effects before water is discharged or reused. Wastewater carries organic matter, nutrients, and suspended particles from communities and industries. Influent is the water entering a treatment system. Effluent is the water leaving it. Their composition determines the treatment required and the quality achieved. \citet{Madhav2019} describe the sources and environmental effects of water pollutants. \citet{Lin2022} examine their different health consequences. These concerns establish why treatment decisions require more than a single measure of effluent quality.''')
paragraph(C1, 'Biological wastewater treatment uses microorganisms', r'''Biological wastewater treatment uses microorganisms to transform organic matter and nutrients. In activated sludge treatment, microorganisms grow as suspended biomass in tanks containing wastewater. A secondary clarifier separates much of this biomass from the treated water by settling. Part of the settled sludge returns to the biological tanks, and another part is withdrawn to control solids accumulation. Organic matter can be oxidized or incorporated into biomass. Nitrogen can move among ammonium, nitrite, nitrate, biomass, and nitrogen gas. Phosphorus can move among dissolved, stored, and particulate forms. \citet{Duan2022} describe biological nitrogen pathways, while \citet{Wentzel1992} explain the connections among nitrogen and phosphorus removal. These interactions require treatment analysis to track several material quantities together.''')
paragraph(C1, 'The activated sludge model (ASM)', r'''The activated sludge model (ASM) family models these changes through component balances and process rates \citep{Henze1987,Henze1999,Henze2006}. A component is a material category tracked by the model, such as dissolved ammonium, soluble organic substrate, or a biomass group. It may combine several chemical species with a common process role. A component state is the collection of their concentrations at a specified location. Process rates describe how quickly biological or chemical transformations consume or produce these components.'''
    + '\n\n' + r'''Reported water quality quantities combine selected components. Chemical oxygen demand (COD) describes oxygen-demand equivalents associated with oxidizable material. Total nitrogen (TN) and total phosphorus (TP) summarize nitrogen and phosphorus on the adopted reporting basis. Total suspended solids (TSS) measures suspended particulate material. Such combined quantities are called composites in this dissertation. They do not identify a unique component state. Two effluents can have the same TN while containing different proportions of ammonium and nitrate. The same total can therefore describe different treatment conditions.''')
paragraph(C1, 'Operating choices influence the entire response.', r'''Operating choices influence the entire treatment response. Hydraulic retention time (HRT) is reactor volume divided by the flow rate specified for that reactor. It describes a nominal liquid residence time. Aeration transfers oxygen into the wastewater for biological reactions. Recycle returns liquid or settled sludge to an earlier treatment location. Wasting withdraws sludge from the plant to control the solids retained \citep{Henze2008}. An operating decision consequently affects several components and locations at once. These relationships matter when predicted effluent quality is used to compare candidate settings.''')
replace(C1, r'\subsection{From process representation to repeated decision calculations}', r'\subsection{From process modeling to repeated operating calculations}')
paragraph(C1, 'Mechanistic models connect operating inputs', r'''Mechanistic models calculate treatment responses from equations for biological conversion, chemical reactions, liquid flow, and solids settling. Their inputs include influent concentrations and operating settings. Their outputs include component concentrations at the treatment locations. A steady-state calculation describes conditions at which modeled inventories no longer change with time under fixed inputs. \citet{Marais1976} establish steady-state activated sludge analysis, and \citet{Hauduc2013} review the process knowledge and limitations of activated sludge modeling. Each calculation remains conditional on its component definitions, parameter values, and system boundary. The system boundary identifies the units and material streams included in the balance.''')
paragraph(C1, 'Several routes can support these comparisons.', r'''Several routes can support these comparisons. An engineer can examine settings through repeated simulation and judgment. Numerical optimization searches for settings that improve a stated objective while satisfying specified limits. For activated sludge operation, the objective can combine effluent quality and resource use. A statistical surrogate is a model fitted to approximate the responses of a more detailed model at lower evaluation cost \citep{BhosekarIerapetritou2018,McBride2019}. In this research, the surrogate predicts component concentrations from influent conditions and operating settings. A feasible setting satisfies the imposed limits. It is not necessarily the best setting. Nonlinear reaction and recycle relationships can create several locally favorable settings, so termination of a numerical search does not establish the best setting over the entire allowed domain.''')
paragraph(C1, 'Statistical surrogates make repeated evaluation', r'''Statistical surrogates learn from paired influent and operating inputs and the corresponding mechanistic treatment responses. Training is the fitting of model parameters to these pairs. A training sample here is one accepted steady-state simulation, rather than a measurement from an operating plant. \citet{Durkin2024} use surrogates in wastewater resource-recovery optimization. \citet{Sundui2021} review biological wastewater applications of machine learning. These developments motivate faster activated sludge calculations while retaining checks on the physical meaning of the predicted component state.''')
paragraph(C1, 'A prediction can be close to a reference response', r'''A prediction can be close to a mechanistic reference while violating a physical requirement. Consider a hypothetical effluent ammonium concentration of $0.2$~g~N~m$^{-3}$ and a prediction of $-0.1$~g~N~m$^{-3}$. Its absolute error is only $0.3$~g~N~m$^{-3}$, but a negative ammonium concentration is physically invalid. Larger substrate or biomass concentrations can dominate an average error score and conceal this problem. A small average error can also conceal a violation of mass conservation distributed across several components \citep{Hansen2024,KircherVotsmeier2025}.''')
paragraph(C1, 'Mass conservation and non-negativity therefore', r'''Mass conservation and non-negativity therefore need separate checks on the same predicted effluent. Mass conservation requires the material entering, leaving, accumulating, and reacting within the system boundary to agree under the adopted component accounting. Stoichiometry specifies the relative amounts consumed and produced by each modeled reaction. A stoichiometric invariant is a weighted combination of components that those reactions do not change. Boundary inputs and outputs must still be included when such a combination is used to check a reactor balance. Non-negativity requires each concentration to be zero or greater. Setting a negative ammonium prediction to zero can disturb the nitrogen balance. Enforcing only a balance can leave one of its component concentrations negative.''')
paragraph(C1, 'Projection provides a defined procedure', r'''Projection adjusts a completed component prediction to satisfy a specified set of constraints. In this research, those constraints include mass conservation and non-negativity. The feasible set contains the concentration states that satisfy the imposed constraints. The projection criterion specifies how changes from the raw prediction are measured. The raw prediction is the output before this adjustment, and the projected prediction is the output afterward. \citet{KircherVotsmeier2025} develop projection for simultaneous mass conservation and non-negativity in mechanistic kinetics surrogates. The method can be applied to different fitted models. Its guarantee concerns the imposed constraints, so it does not establish that the adjusted ammonium, substrate, or biomass concentrations reproduce every reaction rate or improve every prediction error.''')
paragraph(C1, 'Training and validation also require', r'''Validation checks predictions against reference responses excluded from the fit being assessed. Internal validation supports model selection, while a held-out assessment set evaluates the selected procedure. In this research, these checks assess agreement with simulated activated sludge responses. They do not establish agreement with a measured plant. Influent concentrations and selected aeration settings are available before a treatment response is calculated. The resulting effluent ammonium concentration is unknown at that point and cannot be supplied as an ordinary predictive input. Information leakage occurs when unavailable outputs or reserved assessment information influence fitting or model selection \citep{Kaufman2012,Newhart2019}. Keeping that information separate makes the assessment more credible. Extrapolation, which means prediction beyond the sampled input range, still requires separate assessment.''')
paragraph(C1, 'Interpretability addresses another requirement.', r'''Interpretability concerns whether the dependence of a prediction on its inputs can be examined. A structured regression separates fitted terms for operation, influent composition, curvature, and component coupling \citep{Rudin2019,Brunton2016}. Curvature allows the predicted response to change at different rates as an input changes. An interaction allows an aeration response to depend on influent loading. Component coupling expresses fitted dependence among outputs such as substrate and biomass concentrations. These terms describe statistical relationships and need not identify biological mechanisms uniquely. Projection can change both a concentration and its sensitivity to an operating input. Interpretation therefore follows the raw regression and the final projected effluent.''')
paragraph(C1, 'The decision problem adds a further concern.', r'''Operating optimization adds a further concern. A search may select an aeration or recycle setting with favorable predicted effluent quality where the surrogate is inaccurate. This can occur even when average held-out error is small. \citet{Alexandrov1998} develop methods for checking and managing model approximations during optimization. \citet{Pedrozo2025} compare surrogate optimization with reference process calculations. Their work supports an independent mechanistic calculation at the selected controls. Mass conservation and non-negativity remain necessary properties of a component prediction. Decision quality also depends on the treatment response and resource demand calculated at the selected setting.''')
paragraph(C1, 'An error score for one reported effluent quantity', r'''An error score for effluent TN alone does not establish accurate ammonium, nitrite, nitrate, and biomass predictions. Component errors can compensate in the total, and errors in small concentrations can be hidden. Accuracy can also depend on the number of reactor cases used for training and on whether an influent or operating setting lies within the sampled ranges. A common assessment of all component concentrations is needed to distinguish these effects while keeping the activated sludge prediction target fixed.''')
paragraph(C1, "Ordinary regression objectives do not impose", r'''Ordinary regression minimizes prediction error without requiring every new activated sludge effluent to satisfy mass conservation or concentration bounds. A residual is the numerical discrepancy in a balance equation. A physical residual penalty adds a cost for that discrepancy during fitting. A finite penalty can reduce violations without eliminating them at every new influent and operating setting \citep{Raissi2019,Hansen2024}. Projection and independent numerical checks are therefore needed to assess both physical requirements on the returned component state.''')
paragraph(C1, 'Coupled coefficients, nonlinear terms, and projection', r'''A regression coefficient is the fitted weight of an input or input product. Its meaning depends on its units and its place in the prediction calculation. For example, a coefficient multiplying aeration and influent substrate describes a different relationship from a coefficient multiplying aeration alone. Component coupling and projection can further change the final predicted ammonium or biomass response. Interpretation must therefore follow the complete calculation. Fitting and validation must also use only the information available for the intended activated sludge prediction.''')
paragraph(C1, 'Separately predicted unit responses can disagree', r'''Separately predicted activated sludge unit responses can disagree at their connections. The predicted clarifier underflow, for example, may imply a return-sludge contribution different from the one predicted at the mixer. Joint projection can impose specified plant balances, but it does not replace all nonlinear reaction and settling equations. An operating search can still select a setting affected by these approximation errors. Selected aeration, recycle, and wasting controls therefore require independent mechanistic evaluation under the same treatment and resource priorities.''')
paragraph(C1, 'The third question asks how an explicit second-order driver', r'''The third question asks how an explicit second-order regression and learned component coupling can support interpretable activated sludge prediction with mass conservation and non-negativity. A second-order regression includes individual inputs, their squares, and pairwise products. Its driver is the fitted expression evaluated before component coupling is applied. The objective is to formulate and examine this model, its fitting problem, and its projection procedure. Interpretation distinguishes the driver, the raw component predictions, and the final projected effluent. Detailed formulations are developed in Chapter~\ref{ch:interpretable}.''')
paragraph(C1, 'The scientific value is a clear connection', r'''The scientific value is a clear connection between predicted activated sludge responses and the component accounting of the mechanistic model. Stoichiometry defines the relative component changes in each reaction. The reactor and plant boundaries define the material streams included in mass conservation. Non-negativity applies to each modeled concentration, including dissolved nutrients and biomass. These explicit requirements make the physical meaning of a predicted treatment state available for examination.''')
paragraph(C1, 'For researchers comparing activated sludge surrogates,', r'''For researchers comparing activated sludge surrogates, the study provides separate evidence for prediction and projection. Models within each assessment receive common influent and operating inputs and predict the same component concentrations. Preprocessing transforms data into the coordinates used for fitting. Tuning selects model settings using internal validation. Both use only the relevant training information. Paired raw and projected effluents identify which differences arise from projection. The reactor and plant assessments retain their specified validation designs, so their scores answer related questions without establishing one shared model ranking.''')
paragraph(C1, 'The design also separates component errors,', r'''The design reports errors for individual component concentrations and for the combined water quality quantities. It also reports mass conservation residuals, negative concentrations, projection displacement, and computational effort. Projection displacement measures how much the concentration vector changes during enforcement. These measures distinguish an accurate treatment prediction from one that requires substantial adjustment to satisfy the imposed balances. Their joint reporting makes the limits of an average effluent error score visible.''')
paragraph(C1, 'The structured regression adds an inspectable model', r'''The structured regression provides an inspectable activated sludge model. Its named terms and component coupling permit direct coefficient and sensitivity calculations. Sensitivity measures the local change in a predicted concentration when an input such as aeration changes. Projection is analyzed as another stage of the returned effluent calculation. This supports examination of the treatment response without treating fitted coefficients as causal biological parameters.''')
paragraph(C1, 'The formulations provide a defined starting point', r'''The formulations provide a defined starting point for examining uncertainty, dynamic activated sludge operation, and other biological treatment configurations. Their value is the separation of physical constraints, statistical agreement, interpretation, and decision evidence. An extension must define its own modeled components and boundary streams. For example, a dynamic treatment model must account for changing reactor and clarifier inventories. It cannot inherit the steady-state reactor or plant guarantees solely because it uses the same learning method.''')
paragraph(C1, 'The research logic begins with a mechanistic', r'''The research begins with a mechanistic activated sludge model and specified ranges of influent concentrations and operating settings. These ranges form the input domain. Each simulated case pairs those inputs with steady-state component concentrations. The pairs support statistical fitting. Reaction stoichiometry and boundary flows supply the mass conservation relations. Non-negativity supplies the concentration requirement. Projection adjusts each raw effluent prediction to satisfy these requirements.''')
paragraph(C1, 'Mechanistic cases supply supervised targets,', r'''The supervised targets are the mechanistic component concentrations paired with known influent and operating inputs. Physical knowledge supplies the requirements used by projection. Error assessment compares predicted ammonium, substrate, biomass, and other concentrations with those targets. Physical checks assess mass conservation, non-negativity, and the additional plant constraints. Structural inspection examines the fitted treatment model. Decision assessment calculates the mechanistic treatment response at the selected controls. The reactor and connected plant use this logic with separately specified predictors and physical boundaries.''')
replace(C1, 'Exploratory simulation informed the connected plant assessment design. Its separate holdout therefore supports descriptive post-selection assessment rather than independent external confirmation.', 'Exploratory simulation informed the connected plant assessment design. Its separate holdout is a reserved set of simulated plant cases. It supports descriptive assessment conditional on those design choices, which is termed post-selection assessment. It does not provide independent external confirmation.')

# Replace modeling synonyms by context, while preserving mathematical and data meanings.
context = {
 'process representation': 'process model',
 'Process representation': 'Process modeling',
 'mechanistic component representation': 'mechanistic component model',
 'mechanistic representation': 'mechanistic model',
 'state representation': 'modeled state',
 'storage-based representation': 'storage-based model',
 'kinetic representation': 'kinetic model',
 'reaction representation': 'reaction model',
 'Reaction representation': 'Reaction modeling',
 'stoichiometric representation': 'stoichiometric model',
 'nonreactive settling representation': 'nonreactive settling model',
 'component and process representation': 'component and process model',
 'aggregate clarifier representation': 'aggregate clarifier model',
 'treatment representations': 'treatment models',
 'component representation': 'component model',
 'fitted representation': 'fitted model',
 'transparent representation': 'transparent model',
 'Transparent representation': 'Transparent model',
 'interpretable raw representation': 'interpretable raw model',
 'Interpretable representations': 'Interpretable models',
 'Local representations': 'Local models',
 'selected representation': 'selected model',
 'reduced representation': 'reduced model',
 'specified representation': 'specified model',
 'declared representation': 'declared model',
 'Representation-specific construction': 'Construction for a specified model',
 'representation choice': 'modeling choice',
 'Those representation results': 'Those approximation results',
 'Boosting instead builds the representation sequentially.': 'Boosting instead builds the model sequentially.',
 'equal representation of every joint biological regime': 'equal sampling of every joint biological regime',
 'No external learned representation is used.': 'No externally pretrained model is used.',
 'actual training representation': 'actual model inputs and training domain',
 'Such a representation allows': 'Such a model allows',
 'inspectable model representation': 'inspectable model',
 'The representation determines': 'The process model determines',
 'the stated representation': 'the stated model',
}
for path in files:
    if path.suffix != '.tex':
        continue
    for old, new in context.items():
        texts[path] = texts[path].replace(old, new)
    texts[path] = texts[path].replace('activated-sludge', 'activated sludge').replace('wastewater-treatment', 'wastewater treatment').replace('machine-learning', 'machine learning')
    texts[path] = texts[path].replace('raw-head', 'raw-regression').replace('raw head', 'raw regression').replace('raw-head', 'raw-regression')

replace('references.bib', 'author = {RIVAS, A and IRIZAR, I and AYESA, E}', 'author = {Rivas, A. and Irizar, I. and Ayesa, E.}')
replace('manuscript.tex', '    \\sc\\large\n    \\noindent \\thesisYear', '    \\large\n    \\noindent \\thesisYear')
paragraph('manuscript.tex', 'Activated sludge treatment links biological conversion,', r'''Activated sludge treatment uses suspended microorganisms to transform pollutants and retains biomass through solids separation and recirculation. Mechanistic models calculate the resulting concentrations from reaction and flow equations. Repeated simulation can be costly when many operating settings are examined. Statistical surrogates are fitted models that approximate these responses with faster evaluation. A small average prediction error can still conceal a mass conservation violation or a negative concentration. This research develops a common framework for prediction, physical enforcement, interpretation, and operating assessment. A steady-state reactor benchmark compares statistical models using different amounts of training data, separate model-selection and assessment partitions, and inputs beyond the training ranges. Projection adjusts each completed prediction to impose mass conservation and non-negative concentrations. Paired assessment distinguishes its effect on prediction error from the size of the adjustment. A structured second-order regression separates operating terms, influent terms, curvature, and fitted dependence among component concentrations. Its prediction procedure distinguishes physical guidance during fitting from constraints imposed on the final state. A connected plant surrogate extends enforcement to the mixer, reactor train, clarifier outlets, and stored solids. Selected operating controls are assessed through independent mechanistic calculations and comparison with direct optimization under common treatment and resource priorities. Predictive accuracy, satisfaction of imposed physical constraints, interpretability, and decision quality remain separate assessment requirements. Physical guarantees apply to the adopted process model and imposed constraints. Treatment outcomes and model performance require empirical assessment.''')

for path, text in texts.items():
    original = path.read_bytes().decode('utf-8').replace('\r\n', '\n')
    if text != original:
        path.write_bytes(text.replace('\n', newlines[path]).encode('utf-8'))
        print(path.relative_to(ROOT))
