from pathlib import Path
from collections import Counter
import json
import re

root = Path(__file__).resolve().parent
source = Path('article/chapters/01_research_problem.tex')
before = source.read_text(encoding='utf-8')
(root / '01_research_problem.before.tex').write_text(before, encoding='utf-8')
paragraphs = before.split('\n\n')
prose = [i for i, p in enumerate(paragraphs) if p and not p.startswith('\\') and not p.startswith('These contributions')]
assert len(prose) == 60
replacements = {
0: r'''Wastewater from communities and industries carries organic matter, nutrients, and suspended particles that must be removed or transformed before the water is discharged or reused. Treatment requirements depend on the composition of the incoming water, called influent, while the quality achieved is assessed in the outgoing water, called effluent. The varied sources and environmental effects of pollutants described by \citet{Madhav2019}, together with the different health consequences examined by \citet{Lin2022}, show why this assessment requires more than a single measure of water quality. Engineers need to understand which materials remain in the effluent and how treatment changes their amounts and forms.''',
1: r'''In the Philippines, these treatment needs are closely tied to the conditions under which infrastructure is financed, managed, and operated. \citet{Tabios2020} discusses the physical setting and governance of Philippine water resources, while \citet{DamalerioBarriers2022} identify technical, financial, social, and institutional barriers to wastewater management in developing countries and relate them to Philippine technology selection. This context motivates methods that help engineers compare treatment alternatives transparently. Faster calculations can support the technical assessment used in planning and operation, although infrastructure and governance barriers also require responses beyond process modeling.''',
2: r'''A useful treatment assessment must therefore consider the resources available to the community or operator alongside the required water quality. The guide edited by \citet{Ulrich2009} connects decentralized treatment requirements with local implementation conditions, and \citet{Jafarinejad2020} considers energy efficiency, cost, reliability, and sustainability within the treatment-design problem. Together, these perspectives place engineering value in the balance between treatment performance and resource use. Prediction accuracy contributes to that assessment, but cannot establish the value of a treatment choice on its own.''',
4: r'''Within the biological tanks, microorganisms use organic substrate for energy or growth, either oxidizing it or incorporating it into biomass. Nutrients also change form as treatment proceeds. Nitrogen moves among ammonium, nitrite, nitrate, biomass, and nitrogen gas through pathways that include nitrification, which oxidizes ammonium to nitrite and nitrate, and denitrification, which converts oxidized nitrogen to nitrogen gas under suitable conditions. Phosphorus moves among dissolved, stored, and particulate forms. The nitrogen pathways described by \citet{Duan2022} and the connections between nitrogen and phosphorus removal explained by \citet{Wentzel1992} show why these transformations must be considered together. Tracking only one material quantity would leave part of the treatment response unexplained.''',
5: r'''The activated sludge model (ASM) family represents these transformations through component balances and process rates \citep{Henze1987,Henze1999,Henze2006}. Each component is a material category, such as dissolved ammonium, soluble organic substrate, or a biomass group, and may combine chemical species that share a process role. Their concentrations at a specified location form the component state. Process rates describe how quickly biological or chemical transformations consume or produce these components, allowing the model to follow the changing composition of the wastewater \citep{Henze2006}.''',
6: r'''Engineers often report water quality through quantities that combine selected components. Chemical oxygen demand (COD) expresses the oxygen-demand equivalents associated with oxidizable material, while total nitrogen (TN) and total phosphorus (TP) summarize their respective nutrients on the adopted reporting basis. Total suspended solids (TSS) measures suspended particulate material \citep{Henze2006,Henze2008}. These combined quantities, called composites in this dissertation, provide useful summaries but do not identify a unique component state. Two effluents with the same TN, for example, can contain different proportions of ammonium and nitrate. A model that reproduces the total may therefore still misrepresent the treatment condition that produces it.''',
7: r'''Operating choices influence both this composition and the movement of material through the plant. Hydraulic retention time (HRT), calculated as reactor volume divided by the flow rate specified for that reactor, describes the nominal liquid residence time. Aeration supplies oxygen for biological reactions, recycle returns liquid or settled sludge to an earlier treatment location, and wasting withdraws sludge to control the solids retained in the plant \citep{Henze2008}. Because these choices affect several components and locations together, comparing candidate settings requires a view of the full treatment response as well as the resulting effluent quality.''',
8: r'''Mechanistic models provide this view by calculating component concentrations from equations for biological conversion, chemical reactions, liquid flow, and solids settling. Given influent concentrations and operating settings, a steady-state calculation describes conditions at which the modeled inventories, or amounts of material held within treatment units, no longer change with time. The steady-state analysis established by \citet{Marais1976} and the process knowledge and limitations reviewed by \citet{Hauduc2013} provide the basis for this approach. Its predictions remain conditional on the adopted component definitions, parameter values, and system boundary, which specifies the units and material streams included in the balance.''',
9: r'''By calculating responses at conditions that have not been directly observed, simulation allows engineers to examine alternatives before choosing a design or operating setting. Model validation for an activated sludge process is addressed by \citet{Calise2020}, while \citet{Rivas2008} connect model-based calculations with treatment-plant design. Using a model for such decisions requires more than obtaining a numerical response. Each candidate setting must be evaluated, its treatment response interpreted, and its feasibility assessed against the intended engineering requirements.''',
10: r'''These comparisons can be made through repeated simulation and engineering judgment or through numerical optimization, which searches for settings that improve a stated objective while satisfying specified limits. For activated sludge operation, that objective can combine effluent quality and resource use, requiring repeated treatment calculations as the search proceeds. A statistical surrogate reduces the cost of these evaluations by approximating the responses of a more detailed model \citep{BhosekarIerapetritou2018,McBride2019}. Here, it predicts component concentrations from influent conditions and operating settings. Whether evaluated with a surrogate or a mechanistic model, a feasible setting satisfies the imposed limits but may not be the best available choice. Nonlinear reactions and recycle relationships can produce several locally favorable settings, so the termination of a numerical search does not establish the best setting across the entire allowed domain \citep{Araujo2013,BuzziFerraris2013}.''',
11: r'''Aeration illustrates the engineering trade-off behind these repeated calculations. Changing oxygen supply can alter substrate removal and nitrification while also changing resource demand. The operating sensitivities examined by \citet{Araujo2013} and the aeration optimization and control strategies reviewed by \citet{Gu2023} place these effects within a broader treatment assessment. A preferred aeration setting consequently depends on the joint treatment response and the declared engineering priorities, rather than on the aeration variable or a single effluent quantity alone.''',
12: r'''To approximate that response, statistical surrogates are trained on paired influent and operating inputs and their corresponding mechanistic outputs \citep{Fang2011,Selerio2026}. Training fits the model parameters to these pairs, with each sample in this research representing an accepted steady-state simulation rather than a measurement from an operating plant. The use of surrogates in wastewater resource-recovery optimization by \citet{Durkin2024} and the biological wastewater applications of machine learning reviewed by \citet{Sundui2021} motivate this route to faster calculations. For activated sludge analysis, however, computational savings must be accompanied by checks on the physical meaning of the predicted component state.''',
14: r'''Physical assessment must therefore check mass conservation and non-negativity separately on the same predicted effluent. Mass conservation requires a consistent account of the material entering, leaving, accumulating, and reacting within the stated system boundary. The reaction accounting comes from stoichiometry, which specifies the relative amounts of components consumed and produced. A weighted combination of components that these reactions leave unchanged is a stoichiometric invariant \citep{Henze2006,SturmWexler2020,SturmWexler2022}. Such invariants provide a basis for balance checks, but their use in a reactor also requires the relevant boundary inputs and outputs to be included \citep{TakacsVanrolleghem2006}.''',
15: r'''Non-negativity imposes a complementary requirement that every concentration be zero or greater. These two requirements must be enforced together because correcting one defect can leave or create another. Replacing a negative ammonium prediction with zero can disturb the nitrogen balance, while imposing a balance alone can still leave individual concentrations negative \citep{Harder2022,KircherVotsmeier2025}.''',
16: r'''Projection provides a way to make this joint adjustment after a fitted model has produced its component prediction. It moves the raw prediction into a feasible set of concentration states that satisfy specified constraints, using a criterion that measures the change from the original prediction. The resulting state is called the projected prediction. In this research, the constraints include mass conservation and non-negativity, following their joint enforcement in reactive-chemistry and activated sludge surrogates \citep{KircherVotsmeier2025,Selerio2026}. The projection developed by \citet{KircherVotsmeier2025} for mechanistic kinetics surrogates can be applied to different fitted models. Its guarantee is tied to the constraints imposed, so an adjusted ammonium, substrate, or biomass concentration need not reproduce every reaction rate or have a smaller prediction error \citep{SturmSilva2024,Selerio2026}.''',
17: r'''Predictive agreement requires its own assessment against reference responses excluded from the fit being evaluated. Internal validation supports model selection, while a held-out assessment set evaluates the selected procedure \citep{Hastie2009,Kaufman2012}. Because the reference responses in this research come from activated sludge simulations, these checks establish agreement with the adopted mechanistic model. Agreement with a measured plant remains a separate question that requires field evidence \citep{Machado2014,Newhart2019}.''',
18: r'''A credible assessment must also reflect the information available when a prediction is requested. Influent concentrations and selected aeration settings are known before the treatment response is calculated, whereas the resulting effluent ammonium concentration is still unknown and cannot be supplied as an ordinary predictive input. Allowing unavailable outputs or reserved assessment information to influence fitting or model selection introduces information leakage \citep{Kaufman2012,Newhart2019}. Keeping this information separate protects the meaning of the assessment, although extrapolation beyond the sampled input range still needs to be examined in its own right.''',
19: r'''Interpretability adds another requirement by asking whether the dependence of a prediction on its inputs can be examined. A structured regression makes fitted terms for operation, influent composition, curvature, and component coupling explicit \citep{Selerio2026}, supporting inspection of the relationships represented by the model \citep{Rudin2019,Brunton2016}. Curvature allows a response to change at different rates as an input changes. Interaction terms allow an aeration response to depend on influent loading, or the material supplied through incoming concentrations and flow. Component coupling represents fitted dependence among outputs such as substrate and biomass concentrations. Together, these terms describe the statistical response, although they need not uniquely identify the biological mechanisms responsible for it.''',
20: r'''This interpretation must continue through physical enforcement because projection can change both a concentration and its sensitivity to an operating input \citep{Selerio2026}. Understanding the returned effluent therefore requires examining how the raw regression response is altered by projection, as well as the relationships expressed by the fitted equation.''',
21: r'''Even a well-assessed predictor introduces a further question when it is used for optimization. A search may select an aeration or recycle setting where predicted effluent quality is favorable but the surrogate is inaccurate, despite a small average held-out error. The methods for checking and managing model approximations developed by \citet{Alexandrov1998} and the comparison with reference process calculations by \citet{Pedrozo2025} support independent mechanistic evaluation at the selected controls. Mass conservation and non-negativity establish necessary properties of the component prediction, while the treatment response and resource demand calculated at the chosen setting determine the quality of the operating decision.''',
22: r'''These concerns motivate a framework that makes fast treatment predictions understandable, physically checked, and usable as complete component states. Methods for statistical approximation, projection, and process optimization are available in the literature \citep{BhosekarIerapetritou2018,KircherVotsmeier2025,Durkin2024}, but their engineering use requires a clear account of what each method establishes. Prediction error measures agreement with a reference, mass conservation and non-negativity test specified physical requirements, interpretation examines the basis of the returned response, and decision assessment evaluates the selected operating choice with the reference model. Connecting these methods allows their evidence to be considered together without treating the different properties as interchangeable.''',
23: r'''The need for this connection becomes more demanding as the analysis moves from a single reactor to a plant. Reactor projection can impose mass conservation and non-negativity on a complete component prediction \citep{Selerio2026}. In a connected plant, the returned response must also reconcile mixing, reactor, clarifier, recycle, and inventory relationships \citep{Alex2008,JeppssonDiehl1996}. A state that is physically acceptable within one unit can still disagree with the material passed to another, making consistency across the unit connections an additional requirement.''',
24: r'''The research follows this progression through three linked capabilities built on a common mechanistic foundation. It first examines statistical approximation and projection of the complete reactor component response. It then develops an interpretable second-order regression and a defined procedure for projecting its predictions. Finally, it extends the analysis to a connected plant surrogate used to examine operating choices and independently evaluate selected controls. This progression connects component prediction and physical constraints with interpretation and the engineering decisions made from the resulting response.''',
25: r'''The intended benefit is a more transparent basis for treatment analysis. Researchers can distinguish the errors of the fitted predictor from the changes introduced by projection, while engineers can inspect the complete returned state and check a selected operating setting with the original process model. Projection establishes mass conservation and non-negativity under its stated assumptions \citep{KircherVotsmeier2025,Selerio2026}. Assessing accuracy, computational cost, and decision quality alongside that guarantee shows what the surrogate can support and where further evaluation is needed.''',
26: r'''The central problem is how to use machine learning surrogates for activated sludge analysis when accurate approximation alone does not establish a usable engineering response. A complete framework must address four connected limitations concerning the prediction target, physical requirements, interpretation, and plant decisions.''',
27: r'''Effluent TN can be predicted accurately even when the underlying ammonium, nitrite, nitrate, and biomass concentrations are poorly represented. Errors can compensate within the total, and discrepancies in small concentrations can be hidden by an aggregate score \citep{Henze2006,Selerio2026}. Agreement also depends on how many reactor cases are available for training and whether the influent and operating inputs lie within the sampled ranges \citep{VieringLoog2023,Li2024}. A shared assessment of the complete component response is therefore needed to distinguish the effects of learner choice, data availability, and input domain while keeping the prediction target fixed.''',
28: r'''Ordinary regression fits predictions by minimizing error, without requiring every new activated sludge effluent to satisfy mass conservation and concentration bounds. Physical penalties can add a fitting cost for a balance residual, which is the numerical discrepancy in a balance equation. A finite penalty may reduce that discrepancy without eliminating violations at every new influent and operating setting \citep{Raissi2019,Hansen2024}. Projection followed by independent numerical checks offers a way to enforce and assess the two physical requirements on the component state actually returned by the model \citep{KircherVotsmeier2025,Selerio2026}.''',
29: r'''An explicit regression equation makes its fitted coefficients visible, but their meaning depends on their units and their role in the complete calculation. A coefficient is the fitted weight of an input or input product, so a term multiplying aeration and influent substrate describes a different relationship from one multiplying aeration alone. Learned component coupling and projection can then alter the ammonium or biomass response produced by those terms \citep{Selerio2026}. Interpretation must follow these stages to explain the final prediction, and the fitting and validation that support it must use only information available for the intended prediction task \citep{Kaufman2012}.''',
30: r'''At plant scale, separately predicted unit responses can disagree about the material passed between them. A predicted clarifier underflow may imply a return-sludge contribution that differs from the one represented at the mixer, even though consistent connections are required by the component-transport and plant models \citep{JeppssonDiehl1996,Alex2008}. Joint projection can reconcile specified plant balances, but satisfaction of these relations leaves full agreement with the mechanistic equations outside the projection guarantee \citep{KircherVotsmeier2025,Selerio2026}. An operating search can consequently select controls affected by remaining approximation errors. Independent mechanistic evaluation of the selected aeration, recycle, and wasting settings, under the same treatment and resource priorities, is needed to assess the decision itself. This follows the distinction between approximation quality and optimization behavior developed in surrogate optimization research \citep{Alexandrov1998,Pedrozo2025}.''',
31: r'''The general objective is to develop a unified framework that connects activated sludge surrogate prediction, projection, interpretation, and operating assessment. Within this framework, mass conservation and non-negativity are explicit requirements, while predictive error and decision quality remain separate assessment endpoints. Four research questions guide its development.''',
32: r'''The first question concerns how accurately different statistical learners approximate the complete reactor component response as training data availability changes and inputs move beyond the sampled domain. The corresponding objective is to establish a benchmark, or defined simulation task for model comparison, with shared component targets, data partitions, and evaluation scales. This provides a consistent basis for examining how learning performance changes across those conditions.''',
33: r'''The second question concerns what projection changes when it is applied to the same raw predictions. Its objective is a paired assessment of mass conservation, non-negativity, prediction error, displacement, and computational cost before and after projection. Keeping the fitted learner fixed allows the effects of physical enforcement to be distinguished from differences between prediction models.''',
34: r'''The third question concerns how an explicit second-order regression with learned component coupling can provide interpretable activated sludge predictions that satisfy mass conservation and non-negativity. Second-order terms represent individual inputs, their squares, and pairwise products, forming a fitted driver that is evaluated before component coupling. The objective is to formulate and examine this model, its fitting problem, and its projection procedure, tracing interpretation from the driver through the raw component prediction to the final projected effluent. Chapter~\ref{ch:interpretable} develops the detailed formulations.''',
35: r'''The fourth question concerns how joint prediction and projection can support operating choices for a connected activated sludge plant. Its objective is to impose the declared unit connections, formulate common engineering priorities, and independently evaluate the controls selected by an operating search. Comparing surrogate-assisted search with direct mechanistic optimization on the original reference basis connects the predicted plant response with the quality of the resulting decisions.''',
36: r'''The scientific value of the study lies in connecting predicted activated sludge responses with the component accounting of the mechanistic model. Reaction stoichiometry defines relative changes among components, while reactor and plant boundaries identify the material streams included in mass conservation. Non-negativity applies to every modeled concentration, including dissolved nutrients and biomass. Making these requirements explicit allows the physical meaning of a predicted treatment state to be examined alongside its agreement with the reference response.''',
37: r'''This connection also makes the limits of a physical guarantee clearer. A state can conserve mass and contain no negative concentrations while still failing to satisfy the full nonlinear kinetic equations. Similarly, a reported nutrient total can differ from the inventory used in mass conservation. Keeping these distinctions explicit supports a more precise interpretation of scientific machine learning in biological wastewater treatment \citep{Henze2006,TakacsVanrolleghem2006}.''',
38: r'''The study provides a comparison design that distinguishes predictive performance from the effects of projection. Within each assessment, models receive common influent and operating inputs and predict the same component concentrations. Preprocessing transforms the data into fitting coordinates, while tuning uses internal validation to choose hyperparameters that control model structure or fitting, rather than the coefficients estimated during training. Both steps use only the relevant training information to avoid information leakage \citep{Kaufman2012}. Paired raw and projected effluents then reveal the changes attributable to physical enforcement. The reactor and plant assessments retain their own validation designs, allowing them to answer related questions without implying a single model ranking across the studies.''',
39: r'''Assessment combines errors in individual components and reported water quality quantities with mass conservation residuals, negative concentrations, projection displacement, and computational effort. Displacement measures how much the concentration vector changes during enforcement, revealing whether a prediction needs substantial adjustment to satisfy the imposed balances. Reporting these measures together makes visible the limitations of an average effluent error score and distinguishes predictive agreement from physical compliance, as illustrated by component-level projection and activated sludge assessments \citep{SturmSilva2024,Selerio2026}.''',
40: r'''The structured regression adds a model whose fitted relationships can be inspected directly. Named terms and learned component coupling support coefficient analysis and sensitivity calculations, where sensitivity measures the local change in a predicted concentration as an input such as aeration changes. Examining projection as a further stage of the effluent calculation carries this interpretation through to the returned response. The resulting analysis explains the fitted treatment relationships without assigning causal biological meanings to the coefficients \citep{Brunton2016,Selerio2026}.''',
41: r'''For engineers comparing operating conditions, a useful plant prediction must maintain a consistent account of material across connected treatment units \citep{Henze2008,Alex2008}. The connected surrogate predicts mixer, reactor, clarifier-outlet, and inventory responses together, and joint projection reconciles specified relations that separate unit predictions can leave inconsistent. Numerical checks then identify mass conservation and non-negativity violations before the response is used in an operating search, providing a clearer basis for evaluating candidate settings.''',
42: r'''Independent mechanistic evaluation extends this assessment to the decisions actually selected, following the use of reference-model checks in surrogate optimization \citep{Alexandrov1998,Pedrozo2025}. It calculates treatment responses at the chosen controls, checks the original engineering requirements, and distinguishes available decisions from failed or ineligible cases. This makes it possible to assess whether a faster search supports the intended operating choice. Claims of lower operating cost or better field treatment still require evaluation of those outcomes.''',
43: r'''This transparent and computationally manageable assessment can also support technical capacity in wastewater planning. Philippine and other resource-limited settings need decisions that connect treatment requirements with the resources and conditions available for implementation \citep{Tabios2020,DamalerioBarriers2022,Ulrich2009}. The framework contributes a way to examine those technical choices, while practical application continues to depend on plant calibration, reliable measurements, operating expertise, and institutional capacity.''',
44: r'''The formulations provide a defined starting point for research on uncertainty, dynamic activated sludge operation, and other biological treatment configurations. Their value lies in keeping physical constraints, statistical agreement, interpretation, and decision evidence distinct as the application changes. Each extension must define its own components and boundary streams. A dynamic treatment model, for example, must account for changing reactor and clarifier inventories \citep{Takacs1991,Alex2008}, so using the same learning method does not by itself carry the steady-state physical guarantees into dynamic operation.''',
45: r'''The first contribution is a common reactor assessment that retains the complete component prediction target while examining changes in data availability and input domain. Reporting component and composite scores gives each its appropriate role, making discrepancies in the underlying state visible even when a reported total is favorable.''',
46: r'''The second contribution is a paired assessment of projection for mass conservation and non-negativity across different learners. Following the projection principles of \citet{KircherVotsmeier2025}, it applies common physical requirements while evaluating mathematical feasibility, displacement, prediction error, and computational cost separately. The contribution lies in organizing these methods and measures for activated sludge analysis, with the underlying projection method drawn from the existing literature.''',
47: r'''The third contribution is an interpretable second-order regression that combines explicit feature groups, learned component coupling, and checked projection. The feature groups make the activated sludge regression available for structural inspection \citep{Selerio2026}, while the fitting formulation distinguishes soft physical penalties from the projection that imposes mass conservation and non-negativity on the returned state. Tracing the complete calculation connects the fitted terms with the response ultimately used for analysis.''',
48: r'''The fourth contribution extends this reasoning to a connected plant through joint projection and independent operating verification. The formulation links unit responses through the declared mixing, reaction-inventory, clarification, and stored-solids relations. Evaluating selected controls with the original mechanistic equations and a common objective then connects the physical meaning of the surrogate state with the quality of the operating decision made from it.''',
49: r'''Table~\ref{tab:introduction_contributions} links each research problem to its methodological contribution and the evidence used to assess it. These assessment measures describe how the contributions are examined, with empirical outcomes reported in the corresponding results chapters.''',
50: r'''The framework begins with a mechanistic activated sludge model evaluated over specified influent concentrations and operating settings, which together define the input domain. Each accepted simulation pairs these known inputs with steady-state component concentrations to provide the data for statistical fitting. Reaction stoichiometry and boundary flows supply the mass conservation relations \citep{Henze2006,SturmWexler2022}, while non-negativity sets the concentration requirement. Projection then adjusts the raw effluent prediction to satisfy both, following the joint enforcement approaches of \citet{KircherVotsmeier2025} and \citet{Selerio2026}.''',
51: r'''The same logic connects prediction with interpretation and operating analysis. A structured predictor exposes fitted terms and sensitivities, and the connected plant formulation adds relations among treatment units and stored solids. An operating search uses the resulting plant response to select controls, which are independently evaluated with the mechanistic model. Each stage provides evidence for a different aspect of the framework, so a successful physical check cannot substitute for a prediction assessment or a reference evaluation of the selected decision.''',
52: r'''Figure~\ref{fig:research_conceptual_logic} shows how process knowledge and training data lead to component prediction, projection, operating choice, and reference evaluation. The accompanying assessment boxes identify the evidence needed to examine prediction error, physical compliance, interpretation, and decision quality throughout this sequence.''',
53: r'''The mechanistic component concentrations serve as supervised targets paired with known influent and operating inputs. Predicted ammonium, substrate, biomass, and other concentrations are compared with these targets to assess error, while separate checks assess mass conservation, non-negativity, and the additional plant constraints. Structural inspection examines the fitted treatment relationships, and decision assessment evaluates the mechanistic response at the selected controls. Both the reactor and connected plant follow this logic, with their predictors and physical boundaries specified separately.''',
54: r'''The study evaluates simulated steady-state responses of a standalone activated sludge reactor and a connected plant with biological reactors, secondary clarification, and recycle streams. Reference responses come from mechanistic equations with fixed process definitions and parameter values. The reactor and plant assessments each use a separately specified operating domain, so their findings are interpreted within the conditions examined.''',
55: r'''The represented state contains organic, nitrogen, phosphorus, oxygen, alkalinity, biomass, and solids coordinates on the adopted model basis. Mass conservation is imposed within that basis and the stated system boundary, and non-negativity applies to the represented concentrations. These requirements define the extent of the physical guarantee. They do not establish complete elemental accounting for unrepresented species, full kinetic feasibility of every projected state, or dynamic stability beyond the specified checks \citep{TakacsVanrolleghem2006,Selerio2026}.''',
56: r'''Predictive agreement in this study is agreement with the selected mechanistic reference under simulated conditions. Establishing performance at an operating treatment plant would require field evidence addressing calibration uncertainty, measurement error, microbial adaptation, and unrepresented reactions \citep{Machado2014,Newhart2019}. Reliable calibration and process understanding therefore remain essential for any practical extension of the framework \citep{Petersen2003,Meijer2004}.''',
57: r'''Exploratory simulation informed the design of the connected plant assessment, so its reserved holdout cases provide descriptive evidence conditional on those design choices. This is termed post-selection assessment. Although fitting and tuning exclude the holdout responses, that separation does not make the assessment an independent external confirmation. Mechanistic evaluation supplies a reference check at the selected controls, while the statistical limitation associated with the assessment design remains.''',
58: r'''Attached-growth treatment, spatial transport, resource-recovery networks, and dynamic control inform the background and possible extensions of the work, but are outside the evaluated case studies. The connected operating problem is confined to the declared plant topology and local numerical assessment. Its findings consequently do not certify a global optimum or establish a new network configuration.''',
59: r'''Numerical examples and conceptual figures are explicitly hypothetical and explain the mathematical operations. Empirical treatment, prediction, optimization, and timing findings are presented separately in the reactor projection, structured-regression, and connected-plant assessments.''',
}

for number, replacement in replacements.items():
    paragraphs[prose[number]] = replacement
after = '\n\n'.join(paragraphs)
after = after.replace(
    'These contributions are mathematical and methodological. Their significance is the capacity to address the stated limitations through a coherent assessment. Empirical superiority over another learner or optimization route is not presumed.',
    'Together, these mathematical and methodological contributions provide a coherent way to examine the stated limitations. Their value is assessed through the evidence outlined above, with comparative performance established by the empirical results rather than presumed from the model formulation.'
)

citations = lambda s: Counter(re.findall(r'\\cite(?:t|p)\{[^}]+\}', s))
structure = lambda s: re.findall(r'\\(?:chapter|section|subsection|label|ref|input)\{[^}]+\}', s)
assert citations(before) == citations(after), 'Citations changed'
assert structure(before) == structure(after), 'Structure or cross-references changed'
assert ':' not in re.sub(r'\\(?:label|ref)\{[^}]+\}', '', after), 'Explanatory colon introduced'
assert not any(term in after for term in ('activated-sludge', 'wastewater-treatment', 'machine-learning'))
with source.open('w', encoding='utf-8', newline='\n') as f:
    f.write(after)
(root / 'validation.json').write_text(json.dumps({
    'revised_prose_paragraphs': len(replacements) + 1,
    'unchanged_citation_commands': sum(citations(before).values()),
    'headings_labels_cross_references_and_figure_inputs_preserved': True,
    'before_words': len(before.split()),
    'after_words': len(after.split()),
}, indent=2), encoding='utf-8')
print((root / 'validation.json').read_text())
